package crypto

import (
	"encoding/hex"
	"fmt"
	"testing"
)

func TestSignProviderInfo(t *testing.T) {
	testCases := []struct {
		name    string
		pubkey  string
		curve   Curve
		version uint
		apdu    string
	}{
		{
			"SELL_TEST",
			"0478d5facdae2305f48795d3ce7d9244f5060d2f800901da5746d1f4177ae8d7bbe63f3870efc0d36af8f91962811e1d8d9df91ce3b3ea2cd9f550c7d465f8b7b3",
			K1Curve{},
			2,
			"0953454c4c5f54455354000478d5facdae2305f48795d3ce7d9244f5060d2f800901da5746d1f4177ae8d7bbe63f3870efc0d36af8f91962811e1d8d9df91ce3b3ea2cd9f550c7d465f8b7b3",
		},
		{
			"TEST_PROVIDER",
			"047c13debdb9e1afac5a82bbe78da6dca98a2e59af8a9a3f827acb8ed325c79a6c5749eff65d4e3470bd2995def771f45426c58eada7227d536feeffb58fa71c24",
			R1Curve{},
			2,
			"0d544553545f50524f564944455201047c13debdb9e1afac5a82bbe78da6dca98a2e59af8a9a3f827acb8ed325c79a6c5749eff65d4e3470bd2995def771f45426c58eada7227d536feeffb58fa71c24",
		},
	}
	for idx, tc := range testCases {
		t.Run(fmt.Sprint("", idx), func(t *testing.T) {
			// When
			apdu, _ := SignProviderInfo(
				tc.name,
				tc.pubkey,
				tc.curve,
				tc.version,
			)

			// Then
			if apdu != tc.apdu {
				t.Fatalf("APDU mismatch!\nExpect \t%s\nGot \t%s", tc.apdu, apdu)
			}
		})
	}
}

func TestSignByLedger(t *testing.T) {
	// Given
	const messageToSign = "Something very important"
	ledgerPrivateKey := ledgerPrivateKey()
	ledgerPublicKey := ledgerPublicKey()

	// When
	signature := SignMessageInRS(messageToSign, ledgerPrivateKey, Raw)

	// Then
	if VerifyRSSignature(ledgerPublicKey, messageToSign, signature, Raw) != true {
		t.Fatalf("Ledger key pair mismatch")
	}
}

func TestSignByLedger2(t *testing.T) {
	// Given
	const messageToSign = "Something very important"
	ledgerPrivateKey := ledgerPrivateKey()
	ledgerPublicKey := ledgerPublicKey()

	// When
	signature := SignMessageInRS(messageToSign, ledgerPrivateKey, Raw)

	// Then
	if VerifyRSSignature2(ledgerPublicKey, []byte(messageToSign), signature) != true {
		t.Fatalf("Ledger key pair mismatch")
	}
}

func TestSignByLedgerCALSignature(t *testing.T) {
	testCases := []struct {
		apduToSign string
		signature  string
	}{
		{ // Generated by ExchangeTool
			"0d544553545f50524f564944455201047c13debdb9e1afac5a82bbe78da6dca98a2e59af8a9a3f827acb8ed325c79a6c5749eff65d4e3470bd2995def771f45426c58eada7227d536feeffb58fa71c24",
			"3045022068e5971fdad78583e7bb28adac09212108966fd2ed4f8ad206499bca59f0ad12022100aed715d306f772524b805dd4f91afc79b4bda1a14f91d90ea78739e05461d6c7",
		},
		{ // From LL integration test
			"0d544553545f50524f564944455201047c13debdb9e1afac5a82bbe78da6dca98a2e59af8a9a3f827acb8ed325c79a6c5749eff65d4e3470bd2995def771f45426c58eada7227d536feeffb58fa71c24",
			"3044022021b47b4634bb37de210d36131584e1e880db343685d7607832dbfc4cb627950702200f9c233cf677f5b1315684240fc33a97d502db9b1591cb5e0138760696baca9b",
		},
		{ // From LL integration test
			"0953454c4c5f54455354000478d5facdae2305f48795d3ce7d9244f5060d2f800901da5746d1f4177ae8d7bbe63f3870efc0d36af8f91962811e1d8d9df91ce3b3ea2cd9f550c7d465f8b7b3",
			"30440220471b035b40dafa095d615998c82202b2bd00fb45670b828f1dda3b68e5b24cc3022022a1c64d02b8c14e1e4cc2d05b00234642c11db3d4461ff5366f5af337cf0ced",
		},
		{ // From Conflunce - Coinify test (using APDU Legacy format - ie without curve type encoded)
			// "07436f696e69667901044f22668f5f321d3784266c932a2a3141c3ec196ddd51f42cf975267eda23d3a8b02170e4c5c70536e7d03ba4e66ee3e1f9d65e772d3217871a830a7cf60da366",
			"07436f696e696679044f22668f5f321d3784266c932a2a3141c3ec196ddd51f42cf975267eda23d3a8b02170e4c5c70536e7d03ba4e66ee3e1f9d65e772d3217871a830a7cf60da366",
			"30450221008e8b2172ddd48e196dbff81ebe8aebc4ec0988f72de1b02da202f3a8d8f33f9c02205273c1d426aeb460fd36a27696aafda68bdff4139886f29e558895ea85527749",
		},
	}

	for idx, tc := range testCases {
		t.Run(fmt.Sprint("", idx), func(t *testing.T) {
			// Given
			apduToSign := tc.apduToSign
			ledgerPublicKey := ledgerPublicKey()

			// When
			signature, _ := hex.DecodeString(tc.signature)
			// {"name":"TEST_PROVIDER","payloadSignatureComputedFormat":"jws","publicKey":{"curve":"secp256r1","data":"047c13debdb9e1afac5a82bbe78da6dca98a2e59af8a9a3f827acb8ed325c79a6c5749eff65d4e3470bd2995def771f45426c58eada7227d536feeffb58fa71c24"},"service":{"appVersion":2,"name":"swap"},"signature":"3045022100b98db808ad2f1a976fd11cdaa2449a059b854720054895e568bf86b0727cd2e2022041c7887b6e423d8b9bbe6d6ca587aa728139ef4b1329bb0c33506031e9951e15"}
			// Then
			if VerifyDERSignature(ledgerPublicKey, apduToSign, signature) != true {
				t.Fatalf("Ledger key pair mismatch")
			}
		})
	}
}

func TestSignByLedger_FromJS_SellApduSigned(t *testing.T) {
	// Given
	const apduToSign = "0953454c4c5f54455354000478d5facdae2305f48795d3ce7d9244f5060d2f800901da5746d1f4177ae8d7bbe63f3870efc0d36af8f91962811e1d8d9df91ce3b3ea2cd9f550c7d465f8b7b3"
	ledgerPublicKey := ledgerPublicKey()

	// When
	signature, _ := hex.DecodeString("30440220471b035b40dafa095d615998c82202b2bd00fb45670b828f1dda3b68e5b24cc3022022a1c64d02b8c14e1e4cc2d05b00234642c11db3d4461ff5366f5af337cf0ced")

	// Then
	if VerifyDERSignature(ledgerPublicKey, apduToSign, signature) != true {
		t.Fatalf("Ledger key pair mismatch")
	}
}

func TestSignByLedger_FromJS_SwapApduSigned(t *testing.T) {
	// Given
	const apduToSign = "09535741505f54455354000478d5facdae2305f48795d3ce7d9244f5060d2f800901da5746d1f4177ae8d7bbe63f3870efc0d36af8f91962811e1d8d9df91ce3b3ea2cd9f550c7d465f8b7b3"
	ledgerPublicKey := ledgerPublicKey()

	// When
	signature, _ := hex.DecodeString("3045022100ba797b55252b083aa730bd8081cfaf0ef92cbc06c2d4c06ebcb1123aeef52fd5022056177dbb406368b232231c346af24184382493ea591092322fc67ec3a2de8d7f")

	// Then
	if VerifyDERSignature(ledgerPublicKey, apduToSign, signature) != true {
		t.Fatalf("Ledger key pair mismatch")
	}
}

func TestCoinConfig(t *testing.T) {
	testCases := []struct {
		config       CoinConfig
		expectedHash string
	}{
		{
			CoinConfig{
				"BTC",
				"Bitcoin",
				nil,
			},
			"0342544307426974636f696e00",
		},
		{
			CoinConfig{
				"ETH",
				"Ethereum",
				&SubConfig{
					"ETH",
					18,
					0,
				},
			},
			"0345544808457468657265756d050345544812",
		},
		{
			CoinConfig{
				"TON",
				"TON",
				nil,
			},
			"03544f4e03544f4e00",
		},
		// "ethereum/erc20/usd_tether__erc20_",
		// "045553445408457468657265756d06045553445406",
		{
			CoinConfig{
				"USDT",
				"Ethereum",
				&SubConfig{
					"USDT",
					6,
					0,
				},
			},
			"045553445408457468657265756d06045553445406",
		},
		{
			CoinConfig{
				"AVAX",
				"Ethereum",
				&SubConfig{
					"AVAX",
					18,
					43114,
				},
			},
			"044156415808457468657265756d0e044156415812000000000000a86a",
		},
	}

	for _, tc := range testCases {
		t.Run(fmt.Sprint(tc.config.Ticker, tc.config.AppName), func(t *testing.T) {
			// serialized_config
			serialized, _ := GenerateCoinConfig(tc.config)

			if serialized != tc.expectedHash {
				t.Fatal("Serialization \nexpected:\t", tc.expectedHash, "\ngot:\t\t", serialized)
			}
		})
	}
}
